# Generated by Django 5.1.4 on 2024-12-20 14:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BaseUUID',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInt',
            fields=[
                (
                    'id',
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                (
                    'base_uuid',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.baseuuid',
                    ),
                ),
            ],
        ),
    ]
