# Generated by Django 5.1.4 on 2024-12-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseInt',
            new_name='BaseIntModel',
        ),
        migrations.RenameModel(
            old_name='BaseUUID',
            new_name='BaseUUIDModel',
        ),
    ]
